package openapi

import (
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/matjeroapps/supplier/internal/contracts"
	"github.com/matjeroapps/supplier/internal/coreclient"
	"github.com/matjeroapps/supplier/internal/supplierapi"
)

func BuildSupplierSpec() (*openapi3.T, error) {
	return BuildDocument(DocumentSpec{
		Title:         "Matjero Supplier API",
		Description:   "OpenAPI contract for the Matjero Supplier API.",
		Authenticated: true,
		Tags:          CommonTags(),
		Routes:        append(ActorRoutes(true), supplierRoutes()...),
	})
}

func supplierRoutes() []RouteSpec {
	return []RouteSpec{
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/profile",
			OperationID: "getSupplierProfile",
			Summary:     "Get the supplier profile",
			Tags:        []string{"Suppliers"},
			Auth:        true,
			Responses:   AuthReadResponses("Supplier profile", supplierapi.SupplierProfileResponse{}),
		},
		{
			Method:      http.MethodPut,
			Path:        "/v1/supplier/profile",
			OperationID: "updateSupplierProfile",
			Summary:     "Update the supplier profile",
			Tags:        []string{"Suppliers"},
			Auth:        true,
			RequestBody: supplierapi.SupplierProfileUpdateRequest{},
			Responses:   AuthOKResponses("Supplier profile updated", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/markets",
			OperationID: "listSupplierMarkets",
			Summary:     "List supplier markets",
			Tags:        []string{"Markets"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.SupplierMarket]("Supplier market collection"),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/locations",
			OperationID: "listSupplierLocations",
			Summary:     "List fulfillment locations",
			Tags:        []string{"Fulfillment Locations"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.FulfillmentLocation]("Fulfillment location collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/locations",
			OperationID: "createSupplierLocation",
			Summary:     "Create a fulfillment location",
			Tags:        []string{"Fulfillment Locations"},
			Auth:        true,
			RequestBody: supplierapi.SupplierLocationCreateRequest{},
			Responses:   AuthCreatedResponses("Fulfillment location created", coreclient.FulfillmentLocation{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/products",
			OperationID: "listSupplierProducts",
			Summary:     "List supplier products",
			Tags:        []string{"Catalog"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.SupplierProduct]("Supplier product collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/products",
			OperationID: "createSupplierProduct",
			Summary:     "Create a supplier product",
			Tags:        []string{"Catalog", "Categories", "Attributes", "Variants", "SKUs"},
			Auth:        true,
			RequestBody: supplierapi.SupplierProductCreateRequest{},
			Responses:   AuthCreatedResponses("Supplier product created", supplierapi.ProductCreateResponse{}),
		},
		{
			Method:      http.MethodPut,
			Path:        "/v1/supplier/products/{id}/categories",
			OperationID: "setSupplierProductCategories",
			Summary:     "Update supplier product categories",
			Tags:        []string{"Categories"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			RequestBody: supplierapi.SupplierProductCategoriesRequest{},
			Responses:   AuthOKResponses("Supplier product categories updated", supplierapi.SupplierProductCategoriesRequest{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/products/{id}/variants",
			OperationID: "createSupplierProductVariant",
			Summary:     "Create a supplier product variant",
			Tags:        []string{"Catalog", "Variants"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			RequestBody: supplierapi.SupplierVariantCreateRequest{},
			Responses:   AuthCreatedResponses("Variant created", coreclient.Variant{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/products/{id}/variants/{variant_id}/skus",
			OperationID: "createSupplierVariantSKU",
			Summary:     "Create a supplier SKU",
			Tags:        []string{"Catalog", "SKUs"},
			Auth:        true,
			Parameters: []ParameterSpec{
				PathStringParam("id", "Product identifier"),
				PathStringParam("variant_id", "Variant identifier"),
			},
			RequestBody: supplierapi.SupplierSKUCreateRequest{},
			Responses:   AuthCreatedResponses("SKU created", coreclient.SKU{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/products/{id}/media",
			OperationID: "createSupplierProductMedia",
			Summary:     "Create supplier product media metadata",
			Tags:        []string{"Catalog", "Media"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			RequestBody: supplierapi.SupplierMediaCreateRequest{},
			Responses:   AuthCreatedResponses("Media metadata created", coreclient.MediaMetadata{}),
		},
		{
			Method:      http.MethodPut,
			Path:        "/v1/supplier/products/{id}/media/{media_id}",
			OperationID: "updateSupplierProductMedia",
			Summary:     "Update supplier product media metadata",
			Tags:        []string{"Catalog", "Media"},
			Auth:        true,
			Parameters: []ParameterSpec{
				PathStringParam("id", "Product identifier"),
				PathStringParam("media_id", "Media identifier"),
			},
			RequestBody: supplierapi.SupplierMediaUpdateRequest{},
			Responses:   AuthOKResponses("Media metadata updated", coreclient.MediaMetadata{}),
		},
		{
			Method:      http.MethodDelete,
			Path:        "/v1/supplier/products/{id}/media/{media_id}",
			OperationID: "deleteSupplierProductMedia",
			Summary:     "Delete supplier product media metadata",
			Tags:        []string{"Catalog", "Media"},
			Auth:        true,
			Parameters: []ParameterSpec{
				PathStringParam("id", "Product identifier"),
				PathStringParam("media_id", "Media identifier"),
			},
			Responses: AuthOKResponses("Media metadata deleted", contracts.StatusResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/products/{id}/readiness",
			OperationID: "getSupplierProductReadiness",
			Summary:     "Evaluate supplier product publication readiness",
			Tags:        []string{"Catalog", "Publication"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			Responses:   AuthReadResponses("Supplier publication readiness", coreclient.SupplierPublication{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/products/{id}/publish",
			OperationID: "publishSupplierProduct",
			Summary:     "Publish supplier product after Core readiness checks",
			Tags:        []string{"Catalog", "Publication"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Product identifier")},
			Responses:   AuthOKResponses("Supplier product published", coreclient.SupplierPublication{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/offers",
			OperationID: "listSupplierOffers",
			Summary:     "List supplier offers",
			Tags:        []string{"Supplier Offers"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.SupplierOffer]("Supplier offer collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/offers",
			OperationID: "createSupplierOffer",
			Summary:     "Create a supplier offer",
			Tags:        []string{"Supplier Offers"},
			Auth:        true,
			RequestBody: supplierapi.SupplierOfferCreateRequest{},
			Responses:   AuthCreatedResponses("Supplier offer created", coreclient.SupplierOffer{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/inventory",
			OperationID: "listSupplierInventory",
			Summary:     "List inventory snapshots",
			Tags:        []string{"Inventory"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.InventorySnapshot]("Inventory snapshot collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/inventory/snapshots",
			OperationID: "createInventorySnapshot",
			Summary:     "Create an inventory snapshot",
			Tags:        []string{"Inventory"},
			Auth:        true,
			RequestBody: supplierapi.InventorySnapshotCreateRequest{},
			Responses:   AuthCreatedResponses("Inventory snapshot created", coreclient.InventorySnapshot{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/inventory/{snapshot_id}/adjustments",
			OperationID: "adjustInventorySnapshot",
			Summary:     "Adjust an inventory snapshot",
			Tags:        []string{"Inventory", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("snapshot_id", "Inventory snapshot identifier")},
			RequestBody: supplierapi.InventoryAdjustmentRequest{},
			Responses:   AuthOKResponses("Inventory adjusted", supplierapi.InventoryAdjustmentResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/inventory/{snapshot_id}/movements",
			OperationID: "listInventoryMovements",
			Summary:     "List inventory movements",
			Tags:        []string{"Inventory", "Audit"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("snapshot_id", "Inventory snapshot identifier"), LimitParam(), OffsetParam()},
			Responses:   ListResponses[coreclient.InventoryMovement]("Inventory movement collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/integrations/sync-jobs",
			OperationID: "createSupplierSyncJob",
			Summary:     "Trigger a catalog import sync job",
			Tags:        []string{"Integrations"},
			Auth:        true,
			RequestBody: supplierapi.CreateSyncJobRequest{},
			Responses:   AuthCreatedResponses("Sync job created", supplierapi.SupplierSyncJobResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/integrations/sync-jobs",
			OperationID: "listSupplierSyncJobs",
			Summary:     "List catalog import sync jobs",
			Tags:        []string{"Integrations"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[supplierapi.SupplierSyncJobResponse]("Sync job collection"),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/integrations/sync-jobs/{id}",
			OperationID: "getSupplierSyncJob",
			Summary:     "Get a single sync job",
			Tags:        []string{"Integrations"},
			Auth:        true,
			Parameters:  []ParameterSpec{PathStringParam("id", "Sync job identifier")},
			Responses:   AuthReadResponses("Sync job", supplierapi.SupplierSyncJobResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/retail-capability",
			OperationID: "getRetailCapability",
			Summary:     "Get the supplier's affiliated retail capability",
			Tags:        []string{"Retail Capability"},
			Auth:        true,
			Responses:   AuthReadResponses("Retail capability", supplierapi.SupplierRetailCapabilityResponse{}),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/retail-capability",
			OperationID: "createRetailCapability",
			Summary:     "Provision an affiliated retail seller",
			Tags:        []string{"Retail Capability"},
			Auth:        true,
			RequestBody: supplierapi.SupplierRetailCapabilityRequest{},
			Responses:   AuthCreatedResponses("Retail capability provisioned", supplierapi.SupplierRetailCapabilityResponse{}),
		},
		{
			Method:      http.MethodGet,
			Path:        "/v1/supplier/stores",
			OperationID: "listSupplierStores",
			Summary:     "List the supplier's affiliated retail stores",
			Tags:        []string{"Retail Capability"},
			Auth:        true,
			Parameters:  []ParameterSpec{LimitParam(), OffsetParam()},
			Responses:   ListResponses[supplierapi.SupplierStoreCreateRequest]("Affiliated store collection"),
		},
		{
			Method:      http.MethodPost,
			Path:        "/v1/supplier/stores",
			OperationID: "createSupplierStore",
			Summary:     "Create an affiliated retail store",
			Tags:        []string{"Retail Capability"},
			Auth:        true,
			RequestBody: supplierapi.SupplierStoreCreateRequest{},
			Responses:   AuthCreatedResponses("Store created", supplierapi.SupplierStoreCreateRequest{}),
		},
	}
}
